// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2/gcs.proto

package com.google.cloud.dialogflow.v2;

public final class GcsProto {
  private GcsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$google/cloud/dialogflow/v2/gcs.proto\022\032" +
      "google.cloud.dialogflow.v2\032\037google/api/f" +
      "ield_behavior.proto\032\034google/api/annotati" +
      "ons.protoB\227\001\n\036com.google.cloud.dialogflo" +
      "w.v2B\010GcsProtoP\001ZDgoogle.golang.org/genp" +
      "roto/googleapis/cloud/dialogflow/v2;dial" +
      "ogflow\370\001\001\242\002\002DF\252\002\032Google.Cloud.Dialogflow" +
      ".V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
